# Generated by Django 5.2.4 on 2025-08-01 08:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(max_length=255, unique=True)),
                ('type_compte', models.CharField(choices=[('epargne', 'Épargne'), ('courant', 'Courant')], max_length=10)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('cloture', 'Clôturé'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Epargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_interet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('periode', models.CharField(choices=[('90', '90 jours'), ('180', '180 jours'), ('360', '360 jours')], max_length=3)),
                ('date_epargne', models.DateField()),
                ('montant_a_percevoir', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_debut_epargne', models.DateField()),
                ('date_fin_epargne', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='en_cours', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epargnes', to='accounts.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('transfert', 'Transfert'), ('virement', 'Virement')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('solde_apres', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.compte')),
            ],
        ),
    ]
