# Generated by Django 5.2.4 on 2025-08-01 08:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duree', models.IntegerField()),
                ('date_octroi', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant_total_a_rembourser', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rembourse', 'Remboursé'), ('impaye', 'Impayé'), ('suspendu', 'Suspendu')], default='en_cours', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='clients.client')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prets', to='products.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('cheque', 'Chèque')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('justificatif_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='loans.pret')),
            ],
        ),
    ]
