# Generated by Django 5.2.4 on 2025-08-01 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creation_compte', 'Création de compte'), ('depot', 'Dépôt'), ('retrait', 'Retrait'), ('pret_accorde', 'Prêt accordé'), ('remboursement', 'Remboursement'), ('echeance_proche', 'Échéance proche'), ('epargne_mature', 'Épargne arrivée à maturité'), ('alerte_securite', 'Alerte sécurité'), ('maintenance', 'Maintenance système'), ('autres', 'Autres')], max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['user', 'lu'], name='notificatio_user_id_cf0127_idx'), models.Index(fields=['type_action'], name='notificatio_type_ac_f47fc8_idx'), models.Index(fields=['date_action'], name='notificatio_date_ac_5f6b4f_idx')],
            },
        ),
    ]
