# Generated by Django 5.2.4 on 2025-08-01 08:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('commerce', 'Commerce'), ('scolaire', 'Scolaire'), ('immobilier', 'Immobilier')], max_length=15)),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frais', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=15)),
                ('duree', models.CharField(choices=[('6', '6 mois'), ('12', '12 mois'), ('24', '24 mois')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='products.condition')),
            ],
        ),
    ]
